name: Continuous Integration and Deployment

on: 
  push: 
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Start SQL Server
        run: |
         docker run -d -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=P@ss_w0rd" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
      

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: 5 '5s'

      - name: Restore dependencies 
        run: dotnet restore

      - name: BuildApp
        run: dotnet build -c Release --no-restore
      
      - name: run automated tests
        env:
           ConnectionStrings__DefaultConnection: Server=localhost; Database=CICDTest;User=sa;Password=P@ss_w0rd;TrustServerCertificate=True;
        run: dotnet test -c Release --no-build
      
      - name: Publish app
        run: dotnet publish -c Release ./Test-CI-CD/Test-CI-CD.csproj -o ./out
      - name: Deploy to azure web apps 
        uses: azure/webapps-deploy@v2
        with: 
          app-name: Match-App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
          package: ./out



      